### ISSUE TITLE
Destroy related dirty bitmaps

### ISSUE THREAD

**Issue by coldfunction** [Cuju-ft/Cuju#1]
In KVM module, the related dirty bitmaps should be released include epoch_dirty_bitmaps. Although in the commit b48e0b7968f6e5b7cd2795a570ab9bcc2d9b1c20 temporarily fix the issue of the kernel panic due to the destruction of related epoch_dirty_bitmaps, just ignore and doesn't really release them.

**Comment by PJTPJT** [comment]
Fixed: https://github.com/Cuju-ft/Cuju/commit/2cb55b2fc6894c1d18ec7ffb75aa7fb7d1dd8e37
