### ISSUE TITLE
suggestions in README

### ISSUE THREAD

**Issue by kenchan13** [Cuju-ft/Cuju#34]
1. add `sudo`  in command if working on `/mnt/` directory
2. remind user to create a directory `/home/[username]/nfsfolder` before exit `/etc/exports` in NFS Node Setup
3. mark all path names as "Code" to increase readability.
Thanks!

**Comment by PJTPJT** [comment]
Thank you for your comment!

About 1:
Yes, we will add sudo mkdir /mnt/nfs on the document.
And add chown+chgrp for /mnt/nfs

About 2:
OK, we will add it

About 3:
Could you give me some examples of "mark all path names as Code"?

Thank you

**Comment by kenchan13** [comment]
e.g. 
After editing these network interfaces, type`/etc/init.d/networking restart` or `reboot`
instead of 
After editing these network interfaces, type "/etc/init.d/networking restart" or reboot

thanks!

**Comment by PJTPJT** [comment]
> 
> 
> e.g.
> After editing these network interfaces, type`/etc/init.d/networking restart` or `reboot`
> instead of
> After editing these network interfaces, type "/etc/init.d/networking restart" or reboot
> 
> thanks!

OK Thank you!  We will check the entire document and replace that

**Comment by coldfunction** [comment]
@kenchan13 you could also give a pull request, then you can be a contributor if it is approved.

**Comment by PJTPJT** [comment]
Done by this commit
https://github.com/Cuju-ft/Cuju/commit/7d4dde5c3b74ec9a21fd5f870db7c688c1b2f183
